version: "3"

services:
  db:
    image: postgres
  drf:
    container_name: drf
    build: djangorest
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./djangorest:/code
    ports:
      - "80:80"
    depends_on:
      - db
  ng:
    container_name: ng
    build: angular
    ports:
      - "8081:80"
